package ftn.graduatethesispolovniautomobili.model.enumeration;

public enum EAdditionalEquipment {
    METALIC_COLOR,
    MULTI_FUNCTIONAL_STEERING_WHEEL,
    CRUISE_CONTROL,
    REMOTE_LOCKING,
    BLUETOOTH,
    CD_CHANGER,
    CAMERA,
    PANORAMIC_ROOF,
    ELECTRIC_WINDOWS,
    ELECTRIC_MIRROS,
    SEAT_HEATING,
    SEAT_COOLING,
    SEAT_MEMORY,
    MASSAGE_SEATS,
    ISOFIX_SYSTEM,
    MATRIX_LIGHTS,
    MULTIMEDIA,
    SPARE_WHEEL,
    HILL_ASSIST

}
